name: Create and publish a Docker image

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  getversion:
    runs-on: ubuntu-latest
    name: Obtain hassio-plejd Version
    outputs:
      build-version: ${{ steps.set-version.outputs.build_version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install requests
      run: pip install requests

    - name: Set Build Version
      id: set-version
      run: python3 find_tag.py >> $GITHUB_OUTPUT


  build:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    if: ${{ needs.getversion.outputs.build-version != '' }}
    needs: getversion
    env:
      NAV_VERSION: ${{ needs.getversion.outputs.build-version }}

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: datagutten
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      id: push_base
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: |
          NAV_VERSION=${{ needs.getversion.outputs.build-version }}
        tags: |
          ghcr.io/datagutten/plejd-mqtt:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/plejd-mqtt:latest
